timezone: America/Los_Angeles
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "JGStew"
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: BigFix
plugins:
  - jekyll-feed
  - jekyll-redirect-from
