---
name: grammar-check

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/grammar-check.yaml"
    branches:
      - master
      - main
  pull_request:
    paths:
      - ".github/workflows/grammar-check.yaml"


jobs:
  grammar-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu

      - name: install harper grammar checker
        run: cargo install --locked --git https://github.com/Automattic/harper.git --branch master --tag v0.23.0 harper-cli

      - name: run harper-cli config
        run: harper-cli config

      - name: add to dictionary
        run: |
          mkdir -p ~/.config/harper-ls
          cat <<EOFEOF >> ~/.config/harper-ls/dictionary.txt
          jgstew
          jgstew's
          BigFix
          ActionScript
          Fixlet
          SCEP
          Strawgate
          Strawgate's
          IOCs
          etc
          MB
          EOFEOF

      - name: run harper-cli lint help
        run: harper-cli lint --help

      - name: run harper grammar checker
        shell: bash
        run: |
          find . -name "*.md" -exec harper-cli lint {} >> harper-lint-output.txt \;
          # cat harper-lint-output.txt

      - name: upload harper lint output
        uses: actions/upload-artifact@v4
        with:
          name: harper-lint-output
          path: harper-lint-output.txt
